-- Inserir as 3 jornadas
INSERT INTO public.journeys (id, title, subtitle, description, icon, theme_color, duration_days, difficulty, category, benefits, is_premium, is_active, display_order)
VALUES 
  ('11111111-1111-1111-1111-111111111111', 'Desafio 21 Dias', 'Transforme sua mente em 3 semanas', 'Uma jornada intensiva de 21 dias para criar novos hábitos mentais, desenvolver resiliência emocional e construir uma base sólida para o bem-estar duradouro.', '🎯', 'primary', 21, 'intermediário', 'transformacao', '["Criar novos hábitos mentais", "Desenvolver resiliência emocional", "Aumentar autoconsciência", "Melhorar regulação emocional", "Construir disciplina mental"]', false, true, 1),
  
  ('22222222-2222-2222-2222-222222222222', 'Sabedoria Estoica', 'Filosofia prática para a vida moderna', 'Explore os ensinamentos atemporais dos grandes filósofos estoicos - Marco Aurélio, Sêneca e Epicteto. Aprenda a aplicar a sabedoria antiga para enfrentar os desafios do mundo moderno.', '🏛️', 'secondary', 14, 'avançado', 'filosofia', '["Desenvolver equanimidade", "Aceitar o que não pode mudar", "Focar no que está sob controle", "Cultivar virtude", "Encontrar paz interior"]', false, true, 2),
  
  ('33333333-3333-3333-3333-333333333333', 'Despertar dos Chakras', 'Equilibre sua energia vital', 'Uma semana dedicada a explorar e equilibrar os 7 chakras principais. Cada dia focamos em um centro energético diferente, com práticas específicas para harmonizar corpo e mente.', '🌈', 'accent', 7, 'iniciante', 'energia', '["Equilibrar centros energéticos", "Aumentar vitalidade", "Promover cura emocional", "Expandir consciência", "Harmonizar corpo e mente"]', false, true, 3);

-- DESAFIO 21 DIAS - 21 dias (activity_type corrigido)
INSERT INTO public.journey_days (journey_id, day_number, title, teaching_text, teaching_author, challenge_title, challenge_description, reflection_prompt, bonus_tip, activity_type, activity_description)
VALUES
  ('11111111-1111-1111-1111-111111111111', 1, 'O Início da Jornada', 'Toda grande jornada começa com um único passo. Hoje você está fazendo uma escolha poderosa: investir em si mesmo. A mudança não acontece de uma vez, mas através de pequenas ações consistentes.', NULL, 'Carta para o Futuro', 'Escreva uma carta para você mesmo do futuro (daqui a 21 dias). Descreva como você espera se sentir e pelo que será grato.', 'O que me motivou a começar esta jornada hoje?', 'Guarde esta carta. Você irá relê-la no último dia.', 'mental', 'Escrita reflexiva e definição de intenções'),
  ('11111111-1111-1111-1111-111111111111', 2, 'Observando a Mente', 'Nossa mente produz entre 60.000 a 80.000 pensamentos por dia. O primeiro passo para a transformação é simplesmente observar - não julgar, apenas notar. Você não é seus pensamentos; você é quem os observa.', NULL, 'Contador de Pensamentos', 'Durante 10 minutos, sente-se em silêncio e observe quantos pensamentos passam. Não julgue, apenas observe.', 'Que tipos de pensamentos aparecem com mais frequência?', 'Se perder a conta, não tem problema.', 'mental', 'Meditação de observação'),
  ('11111111-1111-1111-1111-111111111111', 3, 'O Poder da Respiração', 'A respiração é a ponte entre o consciente e o inconsciente. Uma respiração lenta e profunda ativa o sistema nervoso parassimpático, trazendo calma instantânea.', NULL, 'Respiração Consciente', 'Pratique a respiração 4-7-8 cinco vezes hoje: inspire por 4 segundos, segure por 7, expire por 8.', 'Como meu corpo se sente antes e depois da prática?', 'Comece com 4-4-6 se for muito intenso.', 'physical', 'Técnica de respiração 4-7-8'),
  ('11111111-1111-1111-1111-111111111111', 4, 'Gratidão Transformadora', 'A gratidão reconecta nosso cérebro. Estudos mostram que pessoas que praticam gratidão têm níveis mais altos de dopamina e serotonina.', NULL, 'Diário de Gratidão', 'Antes de dormir, escreva 3 coisas pelas quais você é grato hoje.', 'Por que essas três coisas me tocaram hoje?', 'Tente não repetir itens nos primeiros dias.', 'mental', 'Prática de gratidão escrita'),
  ('11111111-1111-1111-1111-111111111111', 5, 'Presença no Momento', 'O passado é memória, o futuro é imaginação. O único momento que realmente existe é agora. A presença é onde a vida acontece.', 'Thich Nhat Hanh', 'Minutos de Presença', 'Escolha uma atividade rotineira e faça-a com 100% de atenção. Note cada sensação.', 'O que percebi quando estava totalmente presente?', 'Quando a mente divagar, gentilmente traga-a de volta.', 'mental', 'Mindfulness em atividades cotidianas'),
  ('11111111-1111-1111-1111-111111111111', 6, 'Aceitação Radical', 'Aceitação significa reconhecer a realidade como ela é. Só podemos mudar aquilo que primeiro aceitamos.', NULL, 'O Que Resisto Persiste', 'Identifique uma situação que você resiste aceitar. Escreva sobre ela e depois: "Eu aceito que isso é parte da minha realidade."', 'O que muda quando paro de lutar contra essa realidade?', 'Aceitação é um processo contínuo.', 'mental', 'Exercício de aceitação'),
  ('11111111-1111-1111-1111-111111111111', 7, 'Revisão da Primeira Semana', 'Você completou uma semana inteira! Cada passo que você deu está criando novos caminhos neurais. A mudança está acontecendo.', NULL, 'Balanço Semanal', 'Qual prática mais ressoou com você? Qual foi mais desafiadora? Escreva sobre sua experiência.', 'O que aprendi sobre mim nesta primeira semana?', 'Não há respostas certas ou erradas.', 'mental', 'Reflexão e integração semanal'),
  ('11111111-1111-1111-1111-111111111111', 8, 'Emoções como Mensageiras', 'Emoções são informações. Raiva pode indicar limites violados, tristeza pode sinalizar perda. Quando ouvimos nossas emoções, acessamos sabedoria profunda.', NULL, 'Diálogo com uma Emoção', 'Escolha uma emoção frequente. Pergunte: "O que você está tentando me dizer?" Escreva a resposta.', 'Que mensagem minhas emoções têm tentado me passar?', 'Trate emoções como visitantes sábios.', 'mental', 'Diálogo interno e inteligência emocional'),
  ('11111111-1111-1111-1111-111111111111', 9, 'O Crítico Interior', 'Todos temos uma voz que critica e julga. Reconhecer o crítico interior é o primeiro passo para se libertar dele.', NULL, 'Nomeando o Crítico', 'Dê um nome ao seu crítico interior. Quando ouvi-lo, diga: "Obrigado pela preocupação, mas eu tenho isso."', 'De onde veio essa voz crítica?', 'Humor é uma ferramenta poderosa.', 'mental', 'Trabalho com partes internas'),
  ('11111111-1111-1111-1111-111111111111', 10, 'Autocompaixão', 'Por que tratamos a nós mesmos com mais dureza do que tratamos amigos? Autocompaixão é reconhecer nossa humanidade compartilhada.', 'Kristin Neff', 'Carta de Compaixão', 'Escreva uma carta para si mesmo como se fosse um amigo amoroso, oferecendo compreensão.', 'Como seria minha vida se eu me tratasse com mais gentileza?', 'Coloque a mão no coração enquanto lê.', 'mental', 'Prática de autocompaixão'),
  ('11111111-1111-1111-1111-111111111111', 11, 'Limites Saudáveis', 'Dizer não é dizer sim para si mesmo. Limites protegem nosso jardim interior.', NULL, 'Mapeando Limites', 'Liste 3 situações onde seus limites são violados. Escreva frases claras para estabelecê-los.', 'O que me impede de estabelecer limites claros?', 'Limites protegem sua energia.', 'social', 'Definição de limites pessoais'),
  ('11111111-1111-1111-1111-111111111111', 12, 'Soltar o Controle', 'Queremos controlar porque temos medo. Quando soltamos a ilusão de controle, ganhamos paz.', NULL, 'Entrega Consciente', 'Identifique algo que você tenta controlar mas não pode. Visualize entregando para algo maior.', 'O que aconteceria se eu confiasse mais na vida?', 'Soltar não é desistir.', 'spiritual', 'Prática de surrender'),
  ('11111111-1111-1111-1111-111111111111', 13, 'Conexão Corpo-Mente', 'O corpo guarda memórias que a mente esquece. Tensões emocionais viram tensões físicas. O corpo não mente.', NULL, 'Escaneamento Corporal', 'Deite-se e suba pelo corpo notando sensações. Onde há tensão? Observe por 15 minutos.', 'Que partes do meu corpo precisam de cuidado?', 'Respire nas áreas tensas.', 'physical', 'Body scan e consciência corporal'),
  ('11111111-1111-1111-1111-111111111111', 14, 'Revisão da Segunda Semana', 'Duas semanas! Você está na metade. Os hábitos estão se formando. Continue!', NULL, 'Celebração do Caminho', 'Liste 5 mudanças que notou em si mesmo. Faça algo gentil por você como celebração.', 'Como me sinto diferente de duas semanas atrás?', 'Reconhecer progresso alimenta motivação.', 'mental', 'Reflexão de meio de jornada'),
  ('11111111-1111-1111-1111-111111111111', 15, 'Propósito e Significado', 'Viktor Frankl descobriu que aqueles com um "porquê" suportam qualquer "como". O significado é criado, não encontrado.', 'Viktor Frankl', 'Meu Ikigai', 'O que você ama? No que é bom? O que o mundo precisa? Onde essas respostas se encontram?', 'Qual significado quero dar à minha vida?', 'Propósito pode mudar ao longo da vida.', 'spiritual', 'Exploração de propósito'),
  ('11111111-1111-1111-1111-111111111111', 16, 'Perdão Libertador', 'Segurar ressentimento é beber veneno esperando que o outro morra. O perdão liberta você.', NULL, 'Ritual de Liberação', 'Escreva uma carta para alguém que você precisa perdoar. Depois: "Eu escolho me libertar deste peso."', 'O que eu ganho soltando esse ressentimento?', 'Perdão é processo, não evento.', 'mental', 'Prática de perdão'),
  ('11111111-1111-1111-1111-111111111111', 17, 'Visualização Criativa', 'O cérebro não distingue entre experiência imaginada e real. A imaginação é ensaio para a realidade.', NULL, 'Eu do Futuro', 'Visualize você daqui a um ano, vivendo seu melhor ano. Como se move? Fala? Se sente?', 'Como seria acordar como essa versão de mim?', 'Mais detalhes = mais poder.', 'creative', 'Visualização guiada'),
  ('11111111-1111-1111-1111-111111111111', 18, 'Ação Alinhada', 'Intenção sem ação é desejo. Ação sem intenção é movimento. Alinhe valores, pensamentos e ações.', NULL, 'Um Passo Concreto', 'Identifique UMA ação concreta alinhada com seus valores para começar amanhã.', 'Que ação me aproxima de quem quero ser?', 'Consistência vence intensidade.', 'mental', 'Planejamento intencional'),
  ('11111111-1111-1111-1111-111111111111', 19, 'Comunidade e Conexão', 'Somos seres sociais. Relacionamentos significativos são o maior preditor de felicidade.', NULL, 'Gratidão Relacional', 'Escolha 3 pessoas importantes. Escreva o que aprecia em cada uma. Compartilhe com pelo menos uma.', 'Como posso nutrir meus relacionamentos?', 'Vulnerabilidade abre portas.', 'social', 'Cultivo de relacionamentos'),
  ('11111111-1111-1111-1111-111111111111', 20, 'Rituais de Sustentação', 'Motivação é temporária; rituais são duradouros. Não precisamos sentir vontade para agir.', NULL, 'Meu Ritual Diário', 'Projete um ritual de 10-15 minutos com suas práticas favoritas. Escreva exatamente o que fará.', 'Que práticas quero manter?', 'Vincule a hábitos existentes.', 'mental', 'Design de ritual pessoal'),
  ('11111111-1111-1111-1111-111111111111', 21, 'Celebração e Continuação', 'Você chegou! 21 dias de crescimento. Mas este não é o fim - é um novo começo.', NULL, 'Relendo a Carta', 'Releia a carta do Dia 1. Compare expectativas com experiência. Escreva uma nova carta para o futuro.', 'Quem eu me tornei? Quem ainda quero me tornar?', 'Refaça esta jornada em 3-6 meses.', 'mental', 'Ritual de conclusão');

-- SABEDORIA ESTOICA - 14 dias
INSERT INTO public.journey_days (journey_id, day_number, title, teaching_text, teaching_author, challenge_title, challenge_description, reflection_prompt, bonus_tip, activity_type, activity_description)
VALUES
  ('22222222-2222-2222-2222-222222222222', 1, 'A Dicotomia do Controle', 'Algumas coisas estão sob nosso controle, outras não. Sob nosso controle: opiniões, motivações, desejos. Fora: corpo, reputação, status.', 'Epicteto', 'Círculos de Controle', 'Desenhe dois círculos: o que controlo e o que não controlo. Liste preocupações em cada um.', 'Quanto da minha energia gasto fora do meu controle?', 'Revise semanalmente.', 'mental', 'Exercício de discernimento estoico'),
  ('22222222-2222-2222-2222-222222222222', 2, 'Premeditação dos Males', 'Hoje encontrarei interferência, ingratidão, deslealdade. Mas não me deixarei perturbar por elas.', 'Marco Aurélio', 'Visualização Negativa', 'Pela manhã, visualize desafios do dia. Para cada um, prepare uma resposta virtuosa.', 'Como me sentiria se perdesse algo que tenho como garantido?', 'Isso aumenta gratidão e resiliência.', 'mental', 'Premeditatio Malorum'),
  ('22222222-2222-2222-2222-222222222222', 3, 'Amor Fati', 'Não busque que as coisas aconteçam como você deseja; deseje que aconteçam como acontecem.', 'Epicteto', 'Abraçando o Destino', 'Pense em evento negativo recente. Escreva 3 maneiras pelas quais ele poderia beneficiá-lo.', 'E se tudo fosse exatamente o que eu precisava?', 'Amor Fati encontra significado na dor.', 'spiritual', 'Reinterpretação de eventos'),
  ('22222222-2222-2222-2222-222222222222', 4, 'Memento Mori', 'Que a morte esteja diante de seus olhos todos os dias. Não desperdiçamos tempo, mas muito dele.', 'Sêneca', 'Reflexão sobre Finitude', 'Se tivesse 1 ano de vida, o que faria diferente? O que pararia de fazer?', 'Se eu morresse hoje, do que me arrependeria?', 'Isso é chamado para viver plenamente.', 'spiritual', 'Contemplação da mortalidade'),
  ('22222222-2222-2222-2222-222222222222', 5, 'As Quatro Virtudes Cardinais', 'Sabedoria, coragem, justiça e temperança. Estas são as virtudes que os estoicos cultivavam.', 'Tradição Estoica', 'Auditoria de Virtudes', 'Avalie-se de 1-10 em cada virtude. Escolha uma ação para fortalecer a mais fraca.', 'Em qual virtude preciso trabalhar mais?', 'Virtude é habilidade - melhora com prática.', 'mental', 'Autoavaliação virtuosa'),
  ('22222222-2222-2222-2222-222222222222', 6, 'O Presente como Palco', 'Caráter é destino. Cada momento é oportunidade de demonstrar quem você escolhe ser.', 'Epicteto', 'Ator Consciente', 'Antes de cada interação: "Como a melhor versão de mim agiria?" Então aja assim.', 'Que personagem estou interpretando na minha vida?', 'Sempre escolhemos nossas respostas.', 'mental', 'Atuação virtuosa'),
  ('22222222-2222-2222-2222-222222222222', 7, 'A Vista de Cima', 'Veja de cima: milhares de vidas, rituais, tempestades. Quão breve e fugaz é tudo!', 'Marco Aurélio', 'Perspectiva Cósmica', 'Imagine ver a Terra do espaço. Deixe seus problemas assumirem sua verdadeira proporção.', 'Quão importantes serão minhas preocupações em 100 anos?', 'Isso contextualiza o sofrimento.', 'spiritual', 'Meditação de perspectiva'),
  ('22222222-2222-2222-2222-222222222222', 8, 'Obstáculos como Caminho', 'O que está no caminho se torna o caminho. Cada obstáculo é oportunidade de virtude.', 'Marco Aurélio', 'Transformando Obstáculos', 'Identifique seu maior obstáculo. Escreva 3 maneiras de usá-lo para crescimento.', 'Que forças este obstáculo me força a desenvolver?', 'Fracassos são as melhores escolas.', 'mental', 'Reframe de desafios'),
  ('22222222-2222-2222-2222-222222222222', 9, 'Ação sobre Paixão', 'Não discuta o que um bom homem deveria ser. Seja um. Filosofia não é palavras - é ação.', 'Marco Aurélio', 'Menos Palavras, Mais Ação', 'Para cada conselho que daria, faça primeiro. Para cada crítica, pergunte: eu faço diferente?', 'Minhas ações estão alinhadas com minhas palavras?', 'Consistência constrói caráter.', 'mental', 'Prática de integridade'),
  ('22222222-2222-2222-2222-222222222222', 10, 'Exame de Consciência', 'À noite, examine-se: Que fraqueza conquistei? A que paixão resisti? Em que estou melhor?', 'Sêneca', 'Diário Estoico Noturno', 'Antes de dormir: O que fiz bem? Onde errei? O que posso melhorar?', 'O que faria diferente se refizesse o dia?', 'Este exame deve ser gentil.', 'mental', 'Reflexão noturna estoica'),
  ('22222222-2222-2222-2222-222222222222', 11, 'Desapego ao Externo', 'Riqueza é ter poucas necessidades. Aquele que menos precisa é mais rico.', 'Sêneca', 'Dia de Simplicidade', 'Passe um dia consumindo o mínimo. Coma simples, evite compras, limite entretenimento.', 'Quanto do que consumo é necessidade vs fuga?', 'Simplicidade voluntária liberta.', 'mental', 'Prática de minimalismo'),
  ('22222222-2222-2222-2222-222222222222', 12, 'Cosmopolitismo Estoico', 'Não sou grego, mas cidadão do mundo. A natureza implantou em nós o amor mútuo.', 'Sêneca', 'Círculos de Preocupação', 'Visualize círculos: você, família, comunidade, humanidade. Faça algo gentil por alguém distante.', 'Como seria tratar todos como família?', 'Expandir círculos amplia humanidade.', 'social', 'Expansão de compaixão'),
  ('22222222-2222-2222-2222-222222222222', 13, 'Preparação para Adversidade', 'Em tempos de segurança, prepare-se para tempos difíceis. Diga: É isso que eu temia?', 'Sêneca', 'Desconforto Voluntário', 'Escolha um desconforto: banho frio, pular refeição, acordar mais cedo. Observe sua mente.', 'O que aprendo quando enfrento desconforto?', 'Desconforto escolhido constrói resiliência.', 'physical', 'Práticas ascéticas moderadas'),
  ('22222222-2222-2222-2222-222222222222', 14, 'A Arte de Viver', 'Filosofia não é discursos, mas escolhas. Cada situação comum é palco para virtude.', 'Marco Aurélio', 'Compromisso Estoico', 'Escolha 3 práticas que mais ressoaram e crie um plano para integrá-las à vida diária.', 'Que ensinamento estoico mais me transformou?', 'Filosofia é para ser vivida.', 'mental', 'Integração de práticas estoicas');

-- DESPERTAR DOS CHAKRAS - 7 dias
INSERT INTO public.journey_days (journey_id, day_number, title, teaching_text, teaching_author, challenge_title, challenge_description, reflection_prompt, bonus_tip, activity_type, activity_description)
VALUES
  ('33333333-3333-3333-3333-333333333333', 1, 'Muladhara - Chakra Raiz', 'Na base da coluna reside o Muladhara. De cor vermelha, governa segurança e conexão com a terra. Elemento: Terra. Mantra: LAM.', 'Tradição Yóguica', 'Aterramento', 'Caminhe descalço na terra por 10 minutos. Visualize raízes crescendo de seus pés ao centro da terra.', 'O que me faz sentir seguro? O que abala minha estabilidade?', 'Alimentos vermelhos nutrem este chakra.', 'spiritual', 'Práticas de aterramento'),
  ('33333333-3333-3333-3333-333333333333', 2, 'Svadhisthana - Chakra Sacral', 'Abaixo do umbigo pulsa o Svadhisthana. Cor laranja, governa criatividade e emoções. Elemento: Água. Mantra: VAM.', 'Tradição Yóguica', 'Fluidez Criativa', 'Dance livremente por uma música inteira. Depois, faça algo criativo sem julgamento.', 'Como me relaciono com prazer e criatividade?', 'Beber água e movimentos fluidos equilibram.', 'creative', 'Dança livre e expressão criativa'),
  ('33333333-3333-3333-3333-333333333333', 3, 'Manipura - Chakra do Plexo Solar', 'No plexo solar brilha o Manipura. Cor amarela dourada, governa autoestima e poder pessoal. Elemento: Fogo. Mantra: RAM.', 'Tradição Yóguica', 'Ignite seu Poder', 'Pratique 10 respirações de fogo pela manhã. Defina 3 intenções claras para o dia.', 'Onde entrego meu poder? Onde preciso me posicionar?', 'Exercícios abdominais fortalecem.', 'physical', 'Respiração de fogo'),
  ('33333333-3333-3333-3333-333333333333', 4, 'Anahata - Chakra Cardíaco', 'No peito floresce o Anahata. Cor verde esmeralda, governa amor e compaixão. Elemento: Ar. Mantra: YAM.', 'Tradição Yóguica', 'Abertura do Coração', 'Pratique meditação de amor-bondade: envie amor para si, alguém querido, neutro, difícil, e todos os seres.', 'Onde meu coração está fechado? Quem preciso perdoar?', 'Abraços longos nutrem este chakra.', 'spiritual', 'Meditação Metta'),
  ('33333333-3333-3333-3333-333333333333', 5, 'Vishuddha - Chakra Laríngeo', 'Na garganta ressoa o Vishuddha. Cor azul celeste, governa comunicação e verdade. Elemento: Éter. Mantra: HAM.', 'Tradição Yóguica', 'Verdade Vocal', 'Cante o mantra HAM por 5 minutos. Depois, tenha uma conversa com total honestidade.', 'Onde engulo minhas palavras? Que verdade preciso expressar?', 'Cantar equilibra este chakra.', 'creative', 'Canto de mantras'),
  ('33333333-3333-3333-3333-333333333333', 6, 'Ajna - Chakra do Terceiro Olho', 'Entre as sobrancelhas brilha o Ajna. Cor índigo, governa intuição e visão interior. Mantra: OM.', 'Tradição Yóguica', 'Visão Interior', 'Em ambiente escuro, foque no ponto entre as sobrancelhas. Escreva uma pergunta e deixe a resposta surgir.', 'Quando minha intuição falou e eu não ouvi?', 'Jejum de telas ativa este chakra.', 'spiritual', 'Meditação no terceiro olho'),
  ('33333333-3333-3333-3333-333333333333', 7, 'Sahasrara - Chakra Coronário', 'No topo da cabeça floresce o Sahasrara. Cor violeta ou branca, é nossa conexão com o divino. Mantra: silêncio.', 'Tradição Yóguica', 'Conexão Cósmica', 'Medite em silêncio por 20 minutos, visualizando luz branca entrando pelo topo da cabeça.', 'Quando me senti conectado a algo maior?', 'Silêncio e serviço altruísta elevam.', 'spiritual', 'Meditação de luz e integração');